PKG_NAME = tap4embedded
PKG_URL = https://framagit.org/fperrad/tap4embedded.git
PKG_VERSION = 4bf8ac5162c36b04d7b682e20df13dfd47c52ef9
PKG_LICENSE = Artistic-2.0

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(MAKE) -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
