PKG_NAME = picol
PKG_URL = https://github.com/dbohdan/picol
PKG_VERSION = 3db4fa485c41e7cc4ec83b648b38d82abf3b7023 # 0.6.1
PKG_LICENSE = MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(MAKE) -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
